# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: !secret mariadb
  purge_keep_days: 30

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  portainer:
    title: Portainer
    url: "http://localhost:9000/#!/2/docker/containers"
    icon: mdi:docker
    require_admin: true
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: "http://localhost:3218"
    require_admin: true
  adminer:
    title: Adminer
    icon: mdi:database
    url: "http://localhost:8080"
    require_admin: true
  zigbee2mqtt:
    title: Zigbee2MQTT
    icon: mdi:zigbee
    url: "http://localhost:8020"
    require_admin: true
  esphome:
    title: ESPHome
    icon: mdi:chip
    url: "http://localhost:6052"
    require_admin: true
  nodered:
    title: Node-RED
    icon: mdi:lan
    url: "http://localhost:1880/"
    require_admin: true
