esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DJYwke3DuXS6YDg0K8MZKRarwqY+MMlAxW6ll+4j+eU="

ota:
  password: "2ce0e0cef35765ee6e133e0de9e88bbc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "vegegVNAC7U0"

captive_portal:
    
binary_sensor:
  - platform: status
    name: ESPHome Hello World Status